### ISSUE TITLE
Update the `stanza.io` dep to the latest version

### ISSUE THREAD

**Issue by vicapow** [purecloudlabs/purecloud-streaming-client#25]

**Comment by vicapow** [comment]
Currently using v9 but v11 is the latest version. This will help cut down on install and build because the current v9 has lots of outdated deps that then get duplicated:

````
  dependencies:
    alt-sasl-digest-md5 "^1.0.0"
    async "^2.5.0"
    browserify-versionify "^1.0.4"
    faye-websocket "^0.11.0"
    hostmeta "^2.0.0"
    iana-hashes "^1.0.2"
    jingle "^3.0.0"
    jxt "^3.1.0"
    jxt-xmpp "^3.3.0"
    jxt-xmpp-types "^3.0.0"
    lodash.assign "^3.0.0"
    lodash.filter "^3.1.0"
    lodash.foreach "^3.0.2"
    lodash.isarray "^3.0.1"
    lodash.uniq "^3.1.0"
    request "^2.53.0"
    sasl-anonymous "^0.1.0"
    sasl-external "^0.1.0"
    sasl-plain "^0.1.0"
    sasl-scram-sha-1 "^1.1.0"
    sasl-x-oauth2 "^0.1.0"
    saslmechanisms "^0.1.1"
    uuid "^3.0.1"
    wildemitter "^1.0.1"
    xhr "^2.0.1"
    xmpp-jid "^1.0.0"
````

**Comment by xdumaine** [comment]
V11 changed a number of things and added additional dependencies in order to support node in addition to browsers, which also complicates the module importing because it provides a separate build specifically for browsers. 

I do have a branch already that has done a lot of the work to upgrade that and other dependencies but just haven’t had the chance to work out all the differences, specifically the build and import differences.

**Comment by xdumaine** [comment]
v11 also requires that I bundle in a polyfill for `fetch`

**Comment by xdumaine** [comment]
Resolved in latest version
